name: rerun-notebooks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron:  '0 7,19 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, "3.10", 3.11]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -U setuptools
          pip3 install -r requirements.txt

      - name: Test with pytest
        run: |
          py.test --nbval-lax notebooks
